---

  - name: Mysql Install 
    yum:  
      name:
        - mysql-server
        - python3
        - python3-PyMySQL
      state: present 

  - name: Copy MySQL config file
    copy:
      src: mysql-server.cnf
      dest: /etc/my.cnf.d/mysql-server.cnf   

  - name: Start Mysql   
    systemd:
      name: mysqld
      state: started
      enabled: yes      
  
  - name: Set MySQL root password
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: ''
      name: 'root'
      password: '12345678'
      state: present
  
  - name: Add MySQL database nextcloud
    mysql_db:
      login_host: 'localhost'
      login_user: 'root'
      login_password: '12345678'
      name: nextcloud
      state: present

  - name: Add mysql user nextcloud
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: '12345678'
      name: nextcloud
      host: 192.168.10.20
      password: nextcloud
      priv: 'nextcloud.*:ALL,GRANT'
      state: present